"""``infrakit init`` command — interactive project scaffolding."""

from __future__ import annotations

import os
from pathlib import Path

import typer
from rich.console import Console

console = Console()

# ---------------------------------------------------------------------------
# YAML templates
# ---------------------------------------------------------------------------

_SERVERLESS_API_TEMPLATE = """\
# infrakit.yaml — generated by `infrakit init`
# Template: serverless-api
#
# Resources:
#   {name}_role   — IAM execution role for the Lambda function
#   {name}_fn     — Python 3.12 Lambda function
#   {name}_api    — HTTP API Gateway with a GET /hello route
#
# Deploy:   infrakit deploy --config infrakit.yaml --auto-approve
# Destroy:  infrakit destroy --config infrakit.yaml --auto-approve

project: {project}
region:  {region}
env:     dev

state:
  backend: local
  path: .infrakit/state.json

services:

  {name}_role:
    type: iam-role
    assumed_by: lambda.amazonaws.com
    policies:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  {name}_fn:
    type: lambda
    runtime: python3.12
    handler: handler.handler
    code: ./src
    memory_mb: 128
    timeout_s: 30
    role: !ref {name}_role.arn
    environment:
      GREETING: "Hello from {project}!"

  {name}_api:
    type: api-gateway
    integration: !ref {name}_fn.arn
    stage: dev
    cors: true
    routes:
      - GET /hello
"""

_DATA_STORE_TEMPLATE = """\
# infrakit.yaml — generated by `infrakit init`
# Template: data-store
#
# Resources:
#   {name}_role    — IAM role for Lambda (read/write DynamoDB)
#   {name}_table   — DynamoDB table (pay-per-request billing)
#   {name}_fn      — Python 3.12 Lambda function wired to the table
#
# Deploy:   infrakit deploy --config infrakit.yaml --auto-approve
# Destroy:  infrakit destroy --config infrakit.yaml --auto-approve

project: {project}
region:  {region}
env:     dev

state:
  backend: local
  path: .infrakit/state.json

services:

  {name}_table:
    type: dynamodb
    billing: pay-per-request
    hash_key: id
    hash_key_type: S

  {name}_role:
    type: iam-role
    assumed_by: lambda.amazonaws.com
    policies:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - inline:
          dynamodb:GetItem,PutItem,DeleteItem,Query,Scan: !ref {name}_table.arn

  {name}_fn:
    type: lambda
    runtime: python3.12
    handler: handler.handler
    code: ./src
    memory_mb: 128
    timeout_s: 30
    role: !ref {name}_role.arn
    environment:
      TABLE_NAME: !ref {name}_table.name
"""

_TEMPLATES: dict[str, str] = {
    "serverless-api": _SERVERLESS_API_TEMPLATE,
    "data-store": _DATA_STORE_TEMPLATE,
}

_TEMPLATE_LABELS: dict[int, str] = {
    1: "serverless-api",
    2: "data-store",
}


# ---------------------------------------------------------------------------
# Command
# ---------------------------------------------------------------------------


def init(
    output: str = typer.Option(
        "infrakit.yaml",
        "--output",
        "-o",
        help="Output filename (default: infrakit.yaml in the current directory).",
    ),
) -> None:
    """Scaffold a new infrakit.yaml for a new project."""
    output_path = Path(output)

    console.print("\n[bold]infrakit init[/bold] — create a new infrakit.yaml\n")

    # 1. Project name
    default_name = Path.cwd().name.replace(" ", "-").lower()
    project = typer.prompt(f"  Project name", default=default_name).strip()
    if not project:
        typer.echo("Project name cannot be empty.", err=True)
        raise typer.Exit(1)

    # Derive a short identifier for resource names (alphanumeric + underscore)
    logical_name = project.replace("-", "_").replace(".", "_").lower()

    # 2. Template
    console.print("\n  Available templates:")
    console.print("    [bold]1[/bold]  serverless-api   IAM role + Lambda + API Gateway")
    console.print("    [bold]2[/bold]  data-store       IAM role + DynamoDB + Lambda\n")
    template_choice_raw = typer.prompt("  Template", default="1").strip()
    try:
        template_choice = int(template_choice_raw)
        template_key = _TEMPLATE_LABELS[template_choice]
    except (ValueError, KeyError):
        typer.echo(f"Invalid choice: {template_choice_raw!r}. Choose 1 or 2.", err=True)
        raise typer.Exit(1)

    # 3. Region
    region = typer.prompt("\n  AWS region", default="us-east-1").strip()

    # 4. Overwrite check
    if output_path.exists():
        overwrite = typer.confirm(
            f"\n  {output_path} already exists. Overwrite?", default=False
        )
        if not overwrite:
            console.print("  Aborted.")
            raise typer.Exit(0)

    # 5. Render and write
    content = _TEMPLATES[template_key].format(
        project=project,
        name=logical_name,
        region=region,
    )
    output_path.write_text(content, encoding="utf-8")

    console.print(f"\n  [green]✓[/green] Created [bold]{output_path}[/bold]")
    console.print(f"    Template:  {template_key}")
    console.print(f"    Project:   {project}")
    console.print(f"    Region:    {region}")
    console.print("\n  Next steps:")
    console.print(f"    infrakit validate --config {output_path}")
    console.print(f"    infrakit plan     --config {output_path}")
    console.print(f"    infrakit deploy   --config {output_path} --auto-approve\n")
